apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami-oci
  namespace: flux-system          # any “source” namespace you already use
spec:
  type: oci
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts
