apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.k3s.home
  application.instanceLabelKey: argocd.argoproj.io/instance
  timeout.reconciliation: "60s"
