apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard-home
  namespace: argocd
spec:
  project: default
  destination:
    namespace: adguard-home  #update namespace name if you wish
    name: in-cluster   #update cluster name if its different
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://k8s.adguard.org/helm/
    targetRevision: "1.1.1"
    chart: adguard-home
    helm:
      values: |
         # --- AdGuard Home Helm Chart Values ---
        # Customize these values based on the chart documentation:
        # https://github.com/AdGuardTeam/AdGuardHome/tree/master/helm

        # Example: Configure persistence for configuration and data (highly recommended)
        persistence:
          enabled: true
          size: 5Gi # Adjust size as needed
          # storageClass: your-storage-class-name # Specify your storage class

        # Example: Configure Ingress for the web UI
        ingress:
          enabled: true
          ingressClassName: nginx # Or your ingress controller class
          hosts:
            - host: adguard.yourdomain.com
              paths:
                - path: /
                  pathType: Prefix
          # tls:
          #   - secretName: adguard-home-tls
          #     hosts:
          #       - adguard.yourdomain.com

        # Example: Configure service type for DNS (ClusterIP, NodePort, LoadBalancer)
        # You will need to point your DNS clients to this service.
        service:
          main:
            type: ClusterIP # Or LoadBalancer/NodePort for external access
            # If using LoadBalancer or NodePort, note the IP/ports to use for DNS
            # loadBalancerIP: "your-lb-ip" # If using LoadBalancer and want a specific IP

        # Example: Configure resource requests and limits
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 128Mi
        #   limits:
        #     cpu: 500m
        #     memory: 512Mi

        # Example: Set username and password (use Secrets in production!)
        # username: admin
        # password: your-secure-adguard-password # CHANGE THIS