apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default
  destination:
    namespace: homepage  #update namespace name if you wish
    name: in-cluster   #update cluster name if its different
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/gethomepage/homepage
    targetRevision: "1.2.0"
    chart: homepage
    helm:
      values:

