apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  destination:
    namespace: prometheus  #update namespace name if you wish
    name: in-cluster   #update cluster name if its different
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "25.20.0"
    chart: prometheus
    helm:
      values: |
        # --- Prometheus Helm Chart Values ---
        # Customize these values based on the chart documentation:
        # https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus

        # Example: Enable persistence (highly recommended)
        server:
          persistentVolume:
            enabled: true
            size: 10Gi # Adjust size based on your data retention needs
            # storageClass: your-storage-class-name # Specify your storage class

        # Example: Configure resource requests and limits
        # server:
        #   resources:
        #     requests:
        #       cpu: 100m
        #       memory: 128Mi
        #     limits:
        #       cpu: 500m
        #       memory: 512Mi

        # Example: Configure service type (ClusterIP, NodePort, LoadBalancer)
        # server:
        #   service:
        #     type: ClusterIP

        # Example: Scrape configurations (you'll need to add targets)
        # server:
        #   extrascrapeconfigs: |
        #     - job_name: 'kubernetes-pods'
        #       kubernetes_sd_configs:
        #       - role: pod
        #       relabel_configs:
        #       - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        #         action: keep
        #         regex: true
        #       - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        #         action: replace
        #         target_label: __metrics_path__
        #         regex: (.+)
        #       - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        #         action: replace
        #         regex: ([^:]+)(?::\d+)?;(\d+)
        #         replacement: $1:$2
        #         target_label: __address__