apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: metallb-system
  source:
    repoURL: https://github.com/AndrewTira/LinuxServerSetup.git
    targetRevision: main
    path: argocd-infrastructure/metallb-config
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
