apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard-home
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: adguard-home
  source:
    repoURL: https://github.com/AndrewTira/LinuxServerSetup.git
    targetRevision: main
    path: argocd/argocd-manifests/adguard-home
    directory:
      recurse: true
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
