apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden
  namespace: argocd
spec:
  project: default
  destination:
    namespace: bitwarden
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.bitwarden.com/
    chart: self-host
    targetRevision: "2025.4.2"
    helm:
      values: |
        global:
          domain: bitwarden.example.com

        controller:
          service:
            type: ClusterIP

        ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          hosts:
            - host: bitwarden.example.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - bitwarden.example.com
              secretName: bitwarden-tls  # Make sure this TLS secret exists

        admin:
          email: "admin@example.com"
          password: "changeme123"  # Use a Kubernetes secret in production

        database:
          enabled: true  # Use Bitwarden's internal SQL Server

