apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: grafana
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 6.61.2
    helm:
      values: |
        adminUser: admin
        adminPassword: admin123  # For production, store in a Kubernetes secret

        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            cert-manager.io/cluster-issuer: "letsencrypt-staging"
          hosts:
            - host: grafana.internal.example.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - grafana.internal.example.com
              secretName: grafana-tls

        service:
          type: ClusterIP

        persistence:
          enabled: true
          size: 1Gi
          accessModes:
            - ReadWriteOnce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
