apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/AndrewTira/LinuxServerSetup.git
    targetRevision: main
    path: argocd/ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
