apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager        # target namespace for the release
spec:
  interval: 15m                  # check for chart updates every 15 min
  chart:
    spec:
      chart: cert-manager
      version: 1.14.4            # exact match to your Argo CD tag (v1.14.4)
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 1h
  install:
    createNamespace: true        # = ArgoCD’s CreateNamespace=true
  values:                        # = helm.values block
    installCRDs: true
