apiVersion: v1
kind: Service
metadata:
  name: adguard-home
  annotations:
    metallb.universe.tf/address-pool: default-pool
spec:
  selector:
    app: adguard-home
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
    - port: 3000
      targetPort: 3000
      name: admin-ui
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
