apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden
  namespace: argocd
spec:
  destination:
    namespace: bitwarden
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitwarden.com/
    chart: self-host
    targetRevision: "2025.5.1"
    helm:
      values: |
        database:
          enabled: true
          mssql:
            edition: "express"
            existingSecret:
              enabled: false
            saPassword: "supersecure"  # Use a Secret in production!
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 200m
                memory: 512Mi
            persistence:
              enabled: false  # No PVC for test/dev

        globalSettings:
          dataProtection__defaultKey__id: "bitwarden-key"
          dataProtection__keys__0__id: "bitwarden-key"
          dataProtection__keys__0__value: "some-256-bit-base64-key=="

        api:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi

        web:
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi

        admin:
          enabled: false
        events:
          enabled: false
        notifications:
          enabled: false
        push:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
