apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden
  namespace: argocd
spec:
  project: default
  destination:
    namespace: bitwarden
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.bitwarden.com/
    chart: self-host
    targetRevision: "2025.4.2"
    helm:
      values: |
        global:
          domain: bitwarden.k3s.home

        controller:
          service:
            type: ClusterIP

        ingress:
          enabled: true
          className: nginx
          annotations:
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          hosts:
            - host: bitwarden.k3s.home
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - bitwarden.k3s.home
              secretName: bitwarden-tls

        # --- ADD THESE VALUES FOR SQL SERVER CONNECTION ---
        mssql:
          host: postgresql.bitwarden.svc.cluster.local # Replace with your SQL Server Service FQDN
          port: 5432 # Default SQL Server port
          database: bitwarden         # The database name for Bitwarden
          username: bitwarden         # Your SQL Server username for Bitwarden
          password: supersecure
          # Reference the secret created above for the password
          # existingSecret: bitwarden-mssql-secret
          # existingSecretKey: mssql-password
          # If your SQL Server uses a self-signed cert or you want to disable strict TLS validation (not recommended for production):
          # trustServerCertificate: true
          # encrypt: false # Set to true if your SQL Server forces encryption