# app-postgresql.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  destination:
    namespace: postgresql
    name: in-cluster
  source:
    repoURL: registry-1.docker.io
    chart: bitnamicharts/postgresql
    targetRevision: 16.7.4  # or latest
    helm:
      values: |
        auth:
          username: vaultwarden
          password: supersecure
          database: vaultwarden
        primary:
          persistence:
            enabled: true
            size: 8Gi
        fullnameOverride: postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
