apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  destination:
    namespace: vaultwarden
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://guerzon.github.io/vaultwarden
    chart: vaultwarden
    targetRevision: "0.32.0"
    helm:
      values: |
        # General application settings
        vaultwarden:
          # This 'domain' is likely used for ingress default hostname or other chart logic,
          # but NOT for the DOMAIN env var directly in this chart.
          domain: "https://vault.k3s.home"

          adminToken: "YOUR_VERY_STRONG_ADMIN_TOKEN_HERE" # Ensure this is correctly templated or from a secret
          allowSignups: "true"
          verifySignup: "false"
          requireEmail: "false"
          logLevel: "info"
        
        DOMAIN: "https://vault.k3s.home"

        # --- THIS IS THE CRITICAL ADDITION/CHANGE ---
        env:
          general:
            DOMAIN: "https://vault.k3s.home" # Sets the DOMAIN environment variable
            # You can set other Vaultwarden environment variables here if needed
            # e.g., WEBSOCKET_ENABLED: "true"

        ingress:
          enabled: true
          className: "nginx"
          hostname: "vault.k3s.home" # This correctly sets the ingress hostname
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          tls:
            - hosts:
                - "vault.k3s.home"
              secretName: "vaultwarden-tls-secret"

        persistence:
          enabled: true
          size: 5Gi
          storageClass: ""

        database:
          type: "postgresql"
          # This connectionString will be used by the chart to set the DATABASE_URL env var
          connectionString: "Host=postgresql.postgresql.svc.cluster.local;Port=5432;Database=vaultwarden;Username=vaultwarden;Password=supersecure;Include Error Detail=True;"

        email:
          enabled: true
          smtpHost: "smtp.gmail.com"
          # ... (rest of your email config) ...

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true