apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/longhorn/longhorn.git
    targetRevision: v1.8.1
    path: deploy/longhorn-crds
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
